name: CI

on: push

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup
        run: |
          cat - <<EOS > debug.properties
          BASE_URL=http://localhost:3000
          GOOGLE_CLIENT_ID=xxxxxxxxx
          EOS

          touch local.properties

          mkdir app/signingConfigs
          cat - <<EOS > app/signingConfigs/release.gradle
          signingConfigs {
            release {
            }
          }
          EOS

      - name: Build
        run: ./gradlew clean assembleDebug

      - name: Lint
        run: ./gradlew lint

